// Generated by gencpp from file imu/ImuValues.msg
// DO NOT EDIT!


#ifndef IMU_MESSAGE_IMUVALUES_H
#define IMU_MESSAGE_IMUVALUES_H

#include <ros/service_traits.h>


#include <imu/ImuValuesRequest.h>
#include <imu/ImuValuesResponse.h>


namespace imu
{

struct ImuValues
{

typedef ImuValuesRequest Request;
typedef ImuValuesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImuValues
} // namespace imu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::imu::ImuValues > {
  static const char* value()
  {
    return "275b655e231692d8ecb55e38089bec1b";
  }

  static const char* value(const ::imu::ImuValues&) { return value(); }
};

template<>
struct DataType< ::imu::ImuValues > {
  static const char* value()
  {
    return "imu/ImuValues";
  }

  static const char* value(const ::imu::ImuValues&) { return value(); }
};


// service_traits::MD5Sum< ::imu::ImuValuesRequest> should match 
// service_traits::MD5Sum< ::imu::ImuValues > 
template<>
struct MD5Sum< ::imu::ImuValuesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::imu::ImuValues >::value();
  }
  static const char* value(const ::imu::ImuValuesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu::ImuValuesRequest> should match 
// service_traits::DataType< ::imu::ImuValues > 
template<>
struct DataType< ::imu::ImuValuesRequest>
{
  static const char* value()
  {
    return DataType< ::imu::ImuValues >::value();
  }
  static const char* value(const ::imu::ImuValuesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::imu::ImuValuesResponse> should match 
// service_traits::MD5Sum< ::imu::ImuValues > 
template<>
struct MD5Sum< ::imu::ImuValuesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::imu::ImuValues >::value();
  }
  static const char* value(const ::imu::ImuValuesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu::ImuValuesResponse> should match 
// service_traits::DataType< ::imu::ImuValues > 
template<>
struct DataType< ::imu::ImuValuesResponse>
{
  static const char* value()
  {
    return DataType< ::imu::ImuValues >::value();
  }
  static const char* value(const ::imu::ImuValuesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMU_MESSAGE_IMUVALUES_H
