// Generated by gencpp from file imu/ImuValuesRequest.msg
// DO NOT EDIT!


#ifndef IMU_MESSAGE_IMUVALUESREQUEST_H
#define IMU_MESSAGE_IMUVALUESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu
{
template <class ContainerAllocator>
struct ImuValuesRequest_
{
  typedef ImuValuesRequest_<ContainerAllocator> Type;

  ImuValuesRequest_()
    : readings()
    , degrees(false)  {
    }
  ImuValuesRequest_(const ContainerAllocator& _alloc)
    : readings(_alloc)
    , degrees(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _readings_type;
  _readings_type readings;

   typedef uint8_t _degrees_type;
  _degrees_type degrees;




  typedef boost::shared_ptr< ::imu::ImuValuesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu::ImuValuesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImuValuesRequest_

typedef ::imu::ImuValuesRequest_<std::allocator<void> > ImuValuesRequest;

typedef boost::shared_ptr< ::imu::ImuValuesRequest > ImuValuesRequestPtr;
typedef boost::shared_ptr< ::imu::ImuValuesRequest const> ImuValuesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu::ImuValuesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu::ImuValuesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu::ImuValuesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu::ImuValuesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu::ImuValuesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu::ImuValuesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu::ImuValuesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu::ImuValuesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu::ImuValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eee453f9dfb8e3b509254c34abfb388e";
  }

  static const char* value(const ::imu::ImuValuesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeee453f9dfb8e3b5ULL;
  static const uint64_t static_value2 = 0x09254c34abfb388eULL;
};

template<class ContainerAllocator>
struct DataType< ::imu::ImuValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu/ImuValuesRequest";
  }

  static const char* value(const ::imu::ImuValuesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu::ImuValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string readings\n\
bool degrees\n\
";
  }

  static const char* value(const ::imu::ImuValuesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu::ImuValuesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.readings);
      stream.next(m.degrees);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuValuesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu::ImuValuesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu::ImuValuesRequest_<ContainerAllocator>& v)
  {
    s << indent << "readings: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.readings);
    s << indent << "degrees: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.degrees);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_MESSAGE_IMUVALUESREQUEST_H
